# Generated by Django 5.2.6 on 2025-09-06 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Tên file log', max_length=255, verbose_name='Tên file')),
                ('file_path', models.CharField(help_text='Đường dẫn đầy đủ đến file log', max_length=500, verbose_name='Đường dẫn file')),
                ('file_size', models.BigIntegerField(help_text='Kích thước file tính bằng bytes', verbose_name='Kích thước file (bytes)')),
                ('total_lines', models.PositiveIntegerField(help_text='Tổng số dòng trong file', verbose_name='Tổng số dòng')),
                ('processed_lines', models.PositiveIntegerField(help_text='Số dòng đã được xử lý thành công', verbose_name='Số dòng đã xử lý')),
                ('failed_lines', models.PositiveIntegerField(default=0, help_text='Số dòng không thể xử lý', verbose_name='Số dòng lỗi')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời gian file được xử lý', verbose_name='Thời gian xử lý')),
                ('processing_time', models.DurationField(blank=True, help_text='Thời gian để xử lý file', null=True, verbose_name='Thời gian xử lý')),
            ],
            options={
                'verbose_name': 'Log File',
                'verbose_name_plural': 'Log Files',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='SqlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(help_text='Tên của database (VD: T24VN, WAY4, EBANK)', max_length=50, verbose_name='Tên Database')),
                ('sql_query', models.TextField(help_text='Câu SQL được thực thi', verbose_name='Câu SQL')),
                ('exec_time_ms', models.PositiveIntegerField(help_text='Thời gian thực thi câu SQL tính bằng milliseconds', verbose_name='Thời gian thực thi (ms)')),
                ('exec_count', models.PositiveIntegerField(help_text='Số lần câu SQL được thực thi', verbose_name='Số lần thực thi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời gian bản ghi được tạo', verbose_name='Thời gian tạo')),
                ('line_number', models.PositiveIntegerField(blank=True, help_text='Số dòng trong file log gốc', null=True, verbose_name='Số dòng trong file')),
            ],
            options={
                'verbose_name': 'SQL Log',
                'verbose_name_plural': 'SQL Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['database_name'], name='logs_sqllog_databas_5e5069_idx'), models.Index(fields=['exec_time_ms'], name='logs_sqllog_exec_ti_1f04b7_idx'), models.Index(fields=['exec_count'], name='logs_sqllog_exec_co_c2f5d8_idx'), models.Index(fields=['created_at'], name='logs_sqllog_created_5120a4_idx')],
            },
        ),
    ]
