# Generated by Django 5.2.6 on 2025-09-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='error_details',
            field=models.TextField(blank=True, help_text='Chi tiết các dòng lỗi không thể xử lý', null=True, verbose_name='Chi tiết lỗi'),
        ),
    ]
