# Generated by Django 5.2.6 on 2025-09-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logfile_error_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqllog',
            name='optimization_suggestion',
            field=models.TextField(blank=True, help_text='Gợi ý tối ưu hóa dựa trên phân tích SQL', null=True, verbose_name='Gợi ý tối ưu hóa'),
        ),
    ]
