# Generated by Django 5.2.6 on 2025-09-06 04:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabasePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(help_text='Tên database được cấp quyền truy cập', max_length=50, verbose_name='Tên Database')),
                ('permission_type', models.CharField(choices=[('read', 'Chỉ đọc'), ('write', 'Đọc và ghi'), ('admin', 'Quản trị')], default='read', help_text='Loại quyền truy cập database', max_length=20, verbose_name='Loại quyền')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Thời gian quyền được cấp', verbose_name='Thời gian cấp quyền')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Thời gian quyền hết hạn (để trống = không hết hạn)', null=True, verbose_name='Hết hạn vào')),
                ('is_active', models.BooleanField(default=True, help_text='Quyền có đang hoạt động không', verbose_name='Quyền hoạt động')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú về quyền này', null=True, verbose_name='Ghi chú')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Người dùng đã cấp quyền này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Cấp quyền bởi')),
                ('user', models.ForeignKey(help_text='Người dùng được cấp quyền', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Quyền Database',
                'verbose_name_plural': 'Quyền Database',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user'], name='logs_databa_user_id_e18cf4_idx'), models.Index(fields=['database_name'], name='logs_databa_databas_d1adb2_idx'), models.Index(fields=['permission_type'], name='logs_databa_permiss_72f899_idx'), models.Index(fields=['is_active'], name='logs_databa_is_acti_2424a6_idx')],
                'unique_together': {('user', 'database_name')},
            },
        ),
    ]
