# Generated by Django 5.2.6 on 2025-09-06 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_customuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mfa_backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách backup codes', verbose_name='MFA Backup Codes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Bật xác thực hai yếu tố', verbose_name='MFA Enabled'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_secret_key',
            field=models.CharField(blank=True, help_text='Secret key cho TOTP', max_length=32, null=True, verbose_name='MFA Secret Key'),
        ),
        migrations.AddField(
            model_name='logfile',
            name='error_count',
            field=models.PositiveIntegerField(default=0, help_text='Số dòng bị lỗi khi xử lý', verbose_name='Số lỗi'),
        ),
        migrations.AddField(
            model_name='logfile',
            name='imported_count',
            field=models.PositiveIntegerField(default=0, help_text='Số logs đã được import thành công', verbose_name='Số logs đã import'),
        ),
        migrations.AddField(
            model_name='logfile',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User đã xử lý file này', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý'),
        ),
        migrations.AddField(
            model_name='logfile',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, help_text='Số logs bị bỏ qua do không có quyền', verbose_name='Số logs bị bỏ qua'),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='file_path',
            field=models.CharField(blank=True, help_text='Đường dẫn đầy đủ đến file log', max_length=500, null=True, verbose_name='Đường dẫn file'),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='processed_lines',
            field=models.PositiveIntegerField(default=0, help_text='Số dòng đã được xử lý thành công', verbose_name='Số dòng đã xử lý'),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='total_lines',
            field=models.PositiveIntegerField(default=0, help_text='Tổng số dòng trong file', verbose_name='Tổng số dòng'),
        ),
    ]
